apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eager-oom-killer.fullname" . }}
  labels:
    {{- include "eager-oom-killer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eager-oom-killer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eager-oom-killer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eager-oom-killer.fullname" . }}
      containers:
        - name: eager-oom-killer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-interval", "{{ .Values.interval }}"]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
